---
- name: configure mc server to start automatically
  hosts: minecraft-servers
  gather_facts: false
  become: true #run as sudo

  tasks:
    - name: create systemd file
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/Minecraft-server

          ExecStart=/usr/bin/java -Xms1G -Xmx2G -jar server.jar nogui

          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
    - name: Reload systemd daemons
      systemd:
        daemon_reload: true
    - name: Enable and start minecraft service
      systemd:
        name: minecraft
        state: started
        enabled: true # this makes it run on boot!

